const HOME_BASE = "/";
const ADMIN_BASE = "/admin";

export const ROUTE_NAMES = {
  HOME: HOME_BASE,
  REGISTER: "register",
  SHOP: "shop",
  PRODUCT: "specific-book",
  CART: "cart",
  PROFILE: "profile",
  ADMIN: ADMIN_BASE,
  ADMIN_BOOKS: "books",
  ADMIN_BOOK_CREATE: "create",
  ADMIN_USERS: "users",
  ADMIN_ORDERS: "orders",
  ADMIN_CATEGORIES: "categories",
  ADMIN_SETTINGS: "settings",
};

export const ROUTES = {
  HOME: HOME_BASE,
  REGISTER: `/${ROUTE_NAMES.REGISTER}`,
  SHOP: `/${ROUTE_NAMES.SHOP}`,
  PRODUCT: `/${ROUTE_NAMES.PRODUCT}`,
  CART: `/${ROUTE_NAMES.CART}`,
  PROFILE: `/${ROUTE_NAMES.PROFILE}`,
  ADMIN: ADMIN_BASE,
  ADMIN_BOOKS: `${ADMIN_BASE}/${ROUTE_NAMES.ADMIN_BOOKS}`,
  ADMIN_BOOK_CREATE: `${ADMIN_BASE}/${ROUTE_NAMES.ADMIN_BOOKS}/${ROUTE_NAMES.ADMIN_BOOK_CREATE}`,
  ADMIN_USERS: `${ADMIN_BASE}/${ROUTE_NAMES.ADMIN_USERS}`,
  ADMIN_ORDERS: `${ADMIN_BASE}/${ROUTE_NAMES.ADMIN_ORDERS}`,
  ADMIN_CATEGORIES: `${ADMIN_BASE}/${ROUTE_NAMES.ADMIN_CATEGORIES}`,
  ADMIN_SETTINGS: `${ADMIN_BASE}/${ROUTE_NAMES.ADMIN_SETTINGS}`,
};
